; This file was automatically generated by ScriptHubImporter.py
<<<<<<< Updated upstream
global g_ImportsGameVersion64 := 584
global g_ImportsGameVersionPostFix64 := ".3"
=======
global g_ImportsGameVersion64 := 579
global g_ImportsGameVersionPostFix64 := ""
>>>>>>> Stashed changes
